// Transforms between BusinessCardData format and database schema
// ============================================
// UPDATED: Clean JSONB Structure
// ============================================
// All fields now use plain values (strings)
// No more nested { value, groups } or { username, groups } objects

import { BusinessCardData } from '../types/business-card';
import { DbBusinessCard, DbShareSettings, DbCustomGroup } from '../types/database';

/**
 * Convert BusinessCardData to database format
 * 
 * ✅ UPDATED: Works with clean JSONB structure
 * - Stores plain values (not nested objects)
 * - No "groups" arrays in custom_fields
 */
export function businessCardToDb(data: BusinessCardData, userId: string, userCode: string): DbBusinessCard {
  // Parse profile image if it exists
  let avatarUrl = null;
  let backgroundImageUrl = null;
  try {
    if (data.personal.profileImage) {
      const profileImageData = JSON.parse(data.personal.profileImage);
      avatarUrl = profileImageData.imageUrl || null;
      // Store the full profileImage data in custom_fields for later retrieval
    }
  } catch (e) {
    // If it's not JSON, treat it as a direct URL
    avatarUrl = data.personal.profileImage || null;
  }

  // Extract portfolio images
  const portfolioImages = data.portfolio
    ?.flatMap(item => item.images || [])
    .filter(Boolean) || [];

  // Extract social URLs (now from plain username strings)
  const linkedinUrl = data.socialChannels?.linkedin 
    ? `https://linkedin.com/in/${data.socialChannels.linkedin}` 
    : null;
  const twitterUrl = data.socialChannels?.twitter 
    ? `https://twitter.com/${data.socialChannels.twitter}` 
    : null;
  const facebookUrl = data.socialChannels?.facebook 
    ? `https://facebook.com/${data.socialChannels.facebook}` 
    : null;

  // Helper to convert empty strings to null
  const emptyToNull = (value: string | undefined | null): string | null => {
    return value && value.trim() !== '' ? value.trim() : null;
  };

  return {
    id: '', // Will be generated by database
    user_id: userId,
    user_code: userCode,
    
    // Map core fields
    name: data.personal.name,
    title: emptyToNull(data.personal.title),
    company_name: emptyToNull(data.personal.businessName),
    bio: emptyToNull(data.personal.bio),
    
    // ✅ UPDATED: Direct access to plain values
    email: emptyToNull(data.contact?.email),
    phone: emptyToNull(data.contact?.phone),
    website_url: null, // Not in current data
    
    avatar_url: avatarUrl,
    background_image_url: backgroundImageUrl,
    
    linkedin_url: linkedinUrl,
    twitter_url: twitterUrl,
    instagram_url: null, // Not in current socialChannels
    facebook_url: facebookUrl,
    
    portfolio_images: portfolioImages.length > 0 ? portfolioImages : null,
    
    // ✅ UPDATED: Store plain values in custom_fields (no "groups" arrays)
    custom_fields: {
      contact: {
        phone: data.contact.phone || '',           // Plain string
        email: data.contact.email || '',           // Plain string
        address: data.contact.address || '',       // Plain string
      },
      socialMessaging: {
        zalo: data.socialMessaging.zalo || '',           // Plain string
        messenger: data.socialMessaging.messenger || '', // Plain string
        telegram: data.socialMessaging.telegram || '',
        whatsapp: data.socialMessaging.whatsapp || '',
        kakao: data.socialMessaging.kakao || '',
        discord: data.socialMessaging.discord || '',
        wechat: data.socialMessaging.wechat || '',
      },
      socialChannels: {
        facebook: data.socialChannels.facebook || '',    // Plain string
        linkedin: data.socialChannels.linkedin || '',
        twitter: data.socialChannels.twitter || '',
        youtube: data.socialChannels.youtube || '',
        tiktok: data.socialChannels.tiktok || '',
      },
      profile: {
        about: data.profile.about || '',                 // Plain string
        serviceAreas: data.profile.serviceAreas || '',
        specialties: data.profile.specialties || '',
        experience: data.profile.experience || '',
        languages: data.profile.languages || '',
        certifications: data.profile.certifications || '',
      },
      portfolio: data.portfolio,
      portfolioCategories: data.portfolioCategories,
      customLabels: data.customLabels,
      profileImage: data.personal.profileImage, // Store original for backward compat
      aiAgentVisible: data.aiAgentVisible,
    },
    
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
}

/**
 * Convert database format to BusinessCardData
 * 
 * ✅ UPDATED: Handles both old and new database formats
 * - If data is object with "value" or "username", extract the value
 * - If data is already plain string, use it directly
 */
export function dbToBusinessCard(db: DbBusinessCard): BusinessCardData {
  const customFields = db.custom_fields || {};
  
  // Helper function to extract value from old or new format
  const extractValue = (field: any): string => {
    if (!field) return '';
    if (typeof field === 'string') return field;  // ✅ New format (plain string)
    if (typeof field === 'object') {
      // ❌ Old format (nested object)
      return field.value || field.username || '';
    }
    return '';
  };

  // Extract contact fields (handle both old and new formats)
  const contact = customFields.contact || {};
  const phone = extractValue(contact.phone);
  const email = extractValue(contact.email);
  const address = extractValue(contact.address);

  // Extract social messaging fields
  const socialMessaging = customFields.socialMessaging || {};
  const messaging = {
    zalo: extractValue(socialMessaging.zalo),
    messenger: extractValue(socialMessaging.messenger),
    telegram: extractValue(socialMessaging.telegram),
    whatsapp: extractValue(socialMessaging.whatsapp),
    kakao: extractValue(socialMessaging.kakao),
    discord: extractValue(socialMessaging.discord),
    wechat: extractValue(socialMessaging.wechat),
  };

  // Extract social channels fields
  const socialChannels = customFields.socialChannels || {};
  const channels = {
    facebook: extractValue(socialChannels.facebook),
    linkedin: extractValue(socialChannels.linkedin),
    twitter: extractValue(socialChannels.twitter),
    youtube: extractValue(socialChannels.youtube),
    tiktok: extractValue(socialChannels.tiktok),
  };

  // Extract profile fields
  const profile = customFields.profile || {};
  const profileData = {
    about: extractValue(profile.about),
    serviceAreas: extractValue(profile.serviceAreas),
    specialties: extractValue(profile.specialties),
    experience: extractValue(profile.experience),
    languages: extractValue(profile.languages),
    certifications: extractValue(profile.certifications),
  };
  
  return {
    personal: {
      name: db.name,
      title: db.title || '',
      businessName: db.company_name || '',
      bio: db.bio || '',
      profileImage: customFields.profileImage || '',
    },
    contact: {
      phone: phone,        // ✅ Plain string
      email: email,        // ✅ Plain string
      address: address,    // ✅ Plain string
    },
    socialMessaging: messaging,  // ✅ Plain strings
    socialChannels: channels,    // ✅ Plain strings
    portfolioCategories: customFields.portfolioCategories || [],
    portfolio: customFields.portfolio || [],
    profile: profileData,        // ✅ Plain strings
    groupShareSettings: customFields.groupShareSettings,
    customLabels: customFields.customLabels,
    aiAgentVisible: customFields.aiAgentVisible,
  };
}

/**
 * Convert share settings to database format
 */
export function shareSettingsToDb(
  data: BusinessCardData,
  userId: string,
  userCode: string
): Partial<DbShareSettings> {
  return {
    user_id: userId,
    user_code: userCode,
    hide_email: false, // Default values, can be customized
    hide_phone: false,
    hide_social: false,
    hide_portfolio: false,
    custom_settings: {
      groupShareSettings: data.groupShareSettings || {},
    },
  };
}

/**
 * Merge share settings back into BusinessCardData
 */
export function mergeShareSettings(
  data: BusinessCardData,
  settings: DbShareSettings | null
): BusinessCardData {
  if (!settings) return data;
  
  return {
    ...data,
    groupShareSettings: settings.custom_settings?.groupShareSettings || data.groupShareSettings,
  };
}
