# ============================================
# GitHub Actions: Weekly Analytics Cleanup
# ============================================
# Automatically cleans up raw analytics data older than 30 days
# Runs every Sunday at 3 AM UTC
# Keeps pre-aggregated data forever
# ============================================

name: Analytics Cleanup

on:
  schedule:
    # Every Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      retention_days:
        description: 'Keep raw data for X days'
        required: false
        default: '30'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cleanup Old Analytics Data
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          RETENTION_DAYS: ${{ github.event.inputs.retention_days || '30' }}
        run: |
          # Call Supabase RPC function to clean up old data
          curl -X POST \
            "${SUPABASE_URL}/rest/v1/rpc/cleanup_old_raw_events" \
            -H "apikey: ${SUPABASE_SERVICE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"retention_days\": ${RETENTION_DAYS}}"
      
      - name: Report Cleanup Results
        run: |
          echo "✅ Analytics cleanup completed!"
          echo "Deleted raw events older than ${RETENTION_DAYS} days"
          echo "Pre-aggregated data is kept forever"

# ============================================
# Setup Instructions
# ============================================
# 1. Go to your GitHub repo
# 2. Settings → Secrets and variables → Actions
# 3. Add secrets:
#    - SUPABASE_URL (e.g., https://xxxxx.supabase.co)
#    - SUPABASE_SERVICE_ROLE_KEY (from Supabase dashboard)
# 4. Save this file as: .github/workflows/analytics-cleanup.yml
# 5. Commit and push
# 6. Workflow runs every Sunday at 3 AM automatically!
#
# Manual Run:
# - Go to Actions tab → Analytics Cleanup → Run workflow
# ============================================

# ============================================
# What This Does
# ============================================
# DELETES:
# • Raw sessions older than 30 days
# • Raw page views older than 30 days
# • Raw clicks older than 30 days
#
# KEEPS FOREVER:
# • Daily aggregated stats
# • All pre-computed summaries
#
# Result: Save storage while keeping historical insights!
# ============================================
